openapi: "3.1.0"
info:
  title: "{project.name} api"
  description: "{project.name} api"
  version: "{project.version}"
servers:
- url: "https://kotlin_mpp_playground"
paths:
  /:
    get:
      description: ""
      responses:
        "302":
          description: "Found <br> Redirect"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "/swagger"
  /browse/{param}:
    get:
      description: ""
      parameters:
      - name: "param"
        in: "path"
        required: true
        schema:
          type: "array"
          items:
            type: "string"
      responses:
        "200":
          description: "OK <br> A file response"
          content:
            application/*:
              schema:
                type: "object"
                format: "binary"
        "404":
          description: "Not Found"
          content:
            text/html:
              schema:
                type: "string"
  /ffm:
    get:
      description: ""
  /heapdump:
    get:
      description: ""
      responses:
        "200":
          description: "OK <br> A file response"
          content:
            application/*:
              schema:
                type: "object"
                format: "binary"
  /info:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /jfr:
    get:
      description: ""
  /profile:
    get:
      description: ""
      responses:
        "200":
          description: "OK <br> A file response"
          content:
            application/*:
              schema:
                type: "object"
                format: "binary"
  /vthreads:
    get:
      description: ""