version: "3.8"

# docker compose -f otel-compose.yml up
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest-alpine
    restart: always
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-log:/var/log/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - otel-clickhouse

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - '9100:9100'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    network_mode: host
    volumes:
      - ./otel-collector-config.yml:/config.yaml
    command:
      - --config=file:/config.yaml

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource,vertamedia-clickhouse-datasource
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: vertamedia-clickhouse-datasource
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    restart: always
    networks:
      - otel-clickhouse
    deploy:
      resources:
        limits:
          memory: 2g
    depends_on:
      - clickhouse

volumes:
  clickhouse-data:
  clickhouse-log:

networks:
  otel-clickhouse: