[versions]
java                           = "21"
kotlin                         = "1.9.0-Beta"
kotlin-ksp                     = "1.9.0-Beta-1.0.11"
kotlin-jvmtarget               = "20"
kotlin-dsl-jvmtarget           = "17"
kotlin-api-version             = "1.9"
kotlin-lang-version            = "1.9"
gradle                         = "8.1.1"
java-vendor                    = "Oracle"
java-jvmArguments              = "--enable-preview"
java-addModules                = "jdk.incubator.concurrent,jdk.incubator.vector"

# Additional metadata
group                          = "dev.suresh"
app-mainclass                  = "dev.suresh.Main"
app-module                     = "dev.suresh.kotlinmpp"
githubProject                  = "https://github.com/sureshg/kotlin-mpp-playground"

# Gradle Dependencies Versions
kotlinx-kover                  = "0.7.0"
zip-prefixer                   = "0.3.1"
ajalt-mordant                  = "2.0.0-beta13"
dokka                          = "1.8.10"
jte                            = "2.3.2"
junit                          = "5.10.0-M1"
kotlinx-atomicfu               = "0.20.2"
kotlinx-coroutines             = "1.7.1"
kotlinx-datetime               = "0.4.0"
kotlinx-serialization          = "1.5.1"
ksp-redacted                   = "1.4.0"
slf4j                          = "2.0.7"
ktfmt                          = "0.44"
google-javaformat              = "1.17.0"

# Plugin versions
benmanes                       = "0.46.0"
foojay-resolver                = "0.5.0"
gradle-enterprise              = "3.13.3"
nexus-publish                  = "1.3.0"
shadow                         = "8.1.1"
spotless                       = "6.19.0"
semver-plugin                  = "0.5.0-alpha.2"
taskinfo                       = "2.1.0"
dependency-analysis            = "1.20.0"
best-practices-plugin          = "0.9"


[libraries]
# External plugins for precompiled script plugins
build-kotlin                    = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin"                       , version.ref = "kotlin"}
build-kotlin-noarg              = { module = "org.jetbrains.kotlin:kotlin-noarg"                               , version.ref = "kotlin"}
build-kotlinx-serialization     = { module = "org.jetbrains.kotlin:kotlin-serialization"                       , version.ref = "kotlin"}
build-kotlinx-atomicfu          = { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin"                    , version.ref = "kotlinx-atomicfu"}
build-dokka                     = { module = "org.jetbrains.dokka:dokka-gradle-plugin"                         , version.ref = "dokka"}
build-kotlin-ksp                = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin"         , version.ref = "kotlin-ksp"}
build-ksp-redacted              = { module = "dev.zacsweers.redacted:redacted-compiler-plugin-gradle"          , version.ref = "ksp-redacted"}
build-benmanesversions          = { module = "com.github.ben-manes:gradle-versions-plugin"                    , version.ref = "benmanes"}
build-gradle-enterprise         = { module = "com.gradle.enterprise:com.gradle.enterprise.gradle.plugin"      , version.ref = "gradle-enterprise" }
build-jte-plugin                = { module = "gg.jte:jte-gradle-plugin"                                       , version.ref = "jte"}
build-nexus-plugin              = { module = "io.github.gradle-nexus:publish-plugin"                          , version.ref = "nexus-publish"}
build-spotless-plugin           = { module = "com.diffplug.spotless:spotless-plugin-gradle"                   , version.ref = "spotless"}
build-shadow-plugin             = { module = "com.github.johnrengelman:shadow"                                , version.ref = "shadow"}
build-taskinfo                  = { module = "org.barfuin.gradle.taskinfo:gradle-taskinfo"                    , version.ref = "taskinfo" }
build-dependencyanalysis        = { module = "com.autonomousapps:dependency-analysis-gradle-plugin"           , version.ref = "dependency-analysis" }
build-bestpractices-plugin      = { module = "com.autonomousapps:plugin-best-practices-plugin"                , version.ref = "best-practices-plugin" }
build-semver-plugin             = { module = "com.javiersc.semver:semver-gradle-plugin"                       , version.ref = "semver-plugin" }
build-zip-prefixer              = { module = "net.e175.klaus:zip-prefixer"                                    , version.ref = "zip-prefixer" }
build-foojay-resolver           = { module = "org.gradle.toolchains:foojay-resolver"                          , version.ref = "foojay-resolver" }
build-kotlinx-kover             = { module = "org.jetbrains.kotlinx:kover-gradle-plugin"                      , version.ref = "kotlinx-kover" }

# Gradle Dependencies
kotlin-bom                    = { module = "org.jetbrains.kotlin:kotlin-bom"                    , version.ref = "kotlin"}
kotlin-stdlib                 = { module = "org.jetbrains.kotlin:kotlin-stdlib"                 , version.ref = "kotlin"}
kotlin-stdlib-jdk8            = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8"            , version.ref = "kotlin"}
kotlin-reflect                = { module = "org.jetbrains.kotlin:kotlin-reflect"                , version.ref = "kotlin"}
kotlin-test                   = { module = "org.jetbrains.kotlin:kotlin-test"                   , version.ref = "kotlin"}
kotlinx-coroutines-core       = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"      , version.ref = "kotlinx-coroutines"}
kotlinx-coroutines-test       = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test"      , version.ref = "kotlinx-coroutines"}
kotlinx-serialization-core    = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core"   , version.ref = "kotlinx-serialization"}
kotlinx-serialization-json    = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json"   , version.ref = "kotlinx-serialization"}
kotlinx-datetime              = { module = "org.jetbrains.kotlinx:kotlinx-datetime"             , version.ref = "kotlinx-datetime"}
kotlinx-atomicfu              = { module = "org.jetbrains.kotlinx:atomicfu"                     , version.ref = "kotlinx-atomicfu"}
ajalt-mordant                 = { module = "com.github.ajalt.mordant:mordant"                   , version.ref = "ajalt-mordant"}
jte-runtime                   = { module = "gg.jte:jte-runtime"                                 , version.ref = "jte" }
junit-bom                     = { module = "org.junit:junit-bom"                                , version.ref = "junit"}
slf4j-api                     = { module = "org.slf4j:slf4j-api"                                , version.ref = "slf4j"}
slf4j-simple                  = { module = "org.slf4j:slf4j-simple"                             , version.ref = "slf4j"}

[plugins]
benmanes                    = { id = "com.github.ben-manes.versions"                         , version.ref = "benmanes" }
jte                         = { id = "gg.jte.gradle"                                         , version.ref = "jte" }
bestpractices               = { id = "com.autonomousapps.plugin-best-practices-plugin"       , version.ref = "best-practices-plugin" }

