server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  application:
    name: boot

  threads:
    virtual:
      enabled: true

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: secret


